import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

/// Implementation of `@TLType`: makes an enum the boxed form of a TL type
/// whose constructors are standalone `@TLObject` structs, one per case.
///
/// Each case must carry exactly one unlabeled payload whose type provides
/// `tlConstructorID` and the bare TL coding initializers (i.e. a
/// `TLConstructed` value, as generated by `@TLObject`). Encoding writes the
/// payload's boxed form; decoding reads the constructor number and
/// dispatches on the payloads' `tlConstructorID`s.
public struct TLTypeMacro: ExtensionMacro {
  public static func expansion(
    of node: AttributeSyntax,
    attachedTo declaration: some DeclGroupSyntax,
    providingExtensionsOf type: some TypeSyntaxProtocol,
    conformingTo protocols: [TypeSyntax],
    in context: some MacroExpansionContext
  ) throws -> [ExtensionDeclSyntax] {
    guard let enumDecl = declaration.as(EnumDeclSyntax.self) else {
      throw macroError(node, "@TLType can only be attached to an enum", id: "wrongDecl")
    }

    var cases: [(name: String, payload: String)] = []
    for member in enumDecl.memberBlock.members {
      guard let caseDecl = member.decl.as(EnumCaseDeclSyntax.self) else { continue }
      for element in caseDecl.elements {
        guard let clause = element.parameterClause, clause.parameters.count == 1,
          let parameter = clause.parameters.first,
          parameter.firstName == nil || parameter.firstName?.text == "_"
        else {
          throw macroError(
            element,
            "every @TLType case must carry exactly one unlabeled @TLObject payload",
            id: "casePayload"
          )
        }
        cases.append((name: element.name.text, payload: parameter.type.trimmedDescription))
      }
    }

    guard !cases.isEmpty else {
      throw macroError(node, "@TLType enums must declare at least one case", id: "emptyEnum")
    }
    var seenPayloads: Set<String> = []
    for caseInfo in cases {
      guard seenPayloads.insert(caseInfo.payload).inserted else {
        throw macroError(
          node,
          "duplicate payload type '\(caseInfo.payload)'; the decoding dispatch would be ambiguous",
          id: "duplicatePayload"
        )
      }
    }

    let idList = cases.map { "\($0.payload).tlConstructorID" }.joined(separator: ", ")
    let idLines = cases.map { "case .\($0.name): return \($0.payload).tlConstructorID" }
    let encodeLines = cases.map {
      """
      case .\($0.name)(let value):
          value.tlEncode(to: &writer)
      """
    }
    let decodeLines = cases.map {
      """
      case \($0.payload).tlConstructorID:
          self = .\($0.name)(try \($0.payload)(tlBareFrom: &reader))
      """
    }

    let declaration: DeclSyntax = """
      extension \(type.trimmed)\(raw: conformanceClause(protocols)) {
          public static var tlConstructorIDs: [UInt32] { [\(raw: idList)] }

          public var tlConstructorID: UInt32 {
              switch self {
              \(raw: idLines.joined(separator: "\n        "))
              }
          }

          public func tlEncode(to writer: inout TLWriter) {
              switch self {
              \(raw: encodeLines.joined(separator: "\n        "))
              }
          }

          public init(tlFrom reader: inout TLReader) throws {
              let constructorID = try reader.readUInt32()
              switch constructorID {
              \(raw: decodeLines.joined(separator: "\n        "))
              default:
                  throw TLError.unexpectedConstructor(found: constructorID, expected: Self.tlConstructorIDs)
              }
          }
      }
      """
    guard let extensionDecl = declaration.as(ExtensionDeclSyntax.self) else {
      throw macroError(node, "internal error: failed to build extension", id: "internal")
    }
    return [extensionDecl]
  }
}
