// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `BadMsgNotification` (2 constructors).
  @TLType
  public indirect enum BadMsgNotificationType: Equatable, Sendable {
    /// `bad_msg_notification#a7eff811 bad_msg_id:long bad_msg_seqno:int error_code:int = BadMsgNotification`
    case badMsgNotification(TL.BadMsgNotification)
    /// `bad_server_salt#edab447b bad_msg_id:long bad_msg_seqno:int error_code:int new_server_salt:long = BadMsgNotification`
    case badServerSalt(TL.BadServerSalt)
  }

  /// TL: `bad_msg_notification#a7eff811 bad_msg_id:long bad_msg_seqno:int error_code:int = BadMsgNotification`
  @TLObject(id: 0xa7eff811)
  public struct BadMsgNotification: Equatable, Sendable {
    public var badMsgId: Int64
    public var badMsgSeqno: Int32
    public var errorCode: Int32
  }

  /// TL: `bad_server_salt#edab447b bad_msg_id:long bad_msg_seqno:int error_code:int new_server_salt:long = BadMsgNotification`
  @TLObject(id: 0xedab447b)
  public struct BadServerSalt: Equatable, Sendable {
    public var badMsgId: Int64
    public var badMsgSeqno: Int32
    public var errorCode: Int32
    public var newServerSalt: Int64
  }
}
