// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `bind_auth_key_inner#75a3f765 nonce:long temp_auth_key_id:long perm_auth_key_id:long temp_session_id:long expires_at:int = BindAuthKeyInner`
  @TLObject(id: 0x75a3f765)
  public struct BindAuthKeyInner: Equatable, Sendable {
    public var nonce: Int64
    public var tempAuthKeyId: Int64
    public var permAuthKeyId: Int64
    public var tempSessionId: Int64
    public var expiresAt: Int32
  }
}
