// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `client_DH_inner_data#6643b654 nonce:int128 server_nonce:int128 retry_id:long g_b:bytes = Client_DH_Inner_Data`
  @TLObject(id: 0x6643b654)
  public struct ClientDHInnerData: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var retryId: Int64
    public var gB: Data
  }
}
