// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `DestroySessionRes` (2 constructors).
  @TLType
  public indirect enum DestroySessionResType: Equatable, Sendable {
    /// `destroy_session_ok#e22045fc session_id:long = DestroySessionRes`
    case destroySessionOk(TL.DestroySessionOk)
    /// `destroy_session_none#62d350c9 session_id:long = DestroySessionRes`
    case destroySessionNone(TL.DestroySessionNone)
  }

  /// TL: `destroy_session_ok#e22045fc session_id:long = DestroySessionRes`
  @TLObject(id: 0xe22045fc)
  public struct DestroySessionOk: Equatable, Sendable {
    public var sessionId: Int64
  }

  /// TL: `destroy_session_none#62d350c9 session_id:long = DestroySessionRes`
  @TLObject(id: 0x62d350c9)
  public struct DestroySessionNone: Equatable, Sendable {
    public var sessionId: Int64
  }
}
