// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `DestroyAuthKeyRes` (3 constructors).
  @TLType
  public indirect enum DestroyAuthKeyResType: Equatable, Sendable {
    /// `destroy_auth_key_ok#f660e1d4 = DestroyAuthKeyRes`
    case destroyAuthKeyOk(TL.DestroyAuthKeyOk)
    /// `destroy_auth_key_none#0a9f2259 = DestroyAuthKeyRes`
    case destroyAuthKeyNone(TL.DestroyAuthKeyNone)
    /// `destroy_auth_key_fail#ea109b13 = DestroyAuthKeyRes`
    case destroyAuthKeyFail(TL.DestroyAuthKeyFail)
  }

  /// TL: `destroy_auth_key_ok#f660e1d4 = DestroyAuthKeyRes`
  @TLObject(id: 0xf660e1d4)
  public struct DestroyAuthKeyOk: Equatable, Sendable {
  }

  /// TL: `destroy_auth_key_none#0a9f2259 = DestroyAuthKeyRes`
  @TLObject(id: 0x0a9f2259)
  public struct DestroyAuthKeyNone: Equatable, Sendable {
  }

  /// TL: `destroy_auth_key_fail#ea109b13 = DestroyAuthKeyRes`
  @TLObject(id: 0xea109b13)
  public struct DestroyAuthKeyFail: Equatable, Sendable {
  }
}
