// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `future_salts#ae500895 req_msg_id:long now:int salts:vector<future_salt> = FutureSalts`
  @TLObject(id: 0xae500895)
  public struct FutureSalts: Equatable, Sendable {
    public var reqMsgId: Int64
    public var now: Int32
    @TLBare @TLBareElements public var salts: [TL.FutureSalt]
  }
}
