// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `future_salt#0949d9dc valid_since:int valid_until:int salt:long = FutureSalt`
  @TLObject(id: 0x0949d9dc)
  public struct FutureSalt: Equatable, Sendable {
    public var validSince: Int32
    public var validUntil: Int32
    public var salt: Int64
  }
}
