// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `MsgDetailedInfo` (2 constructors).
  @TLType
  public indirect enum MsgDetailedInfoType: Equatable, Sendable {
    /// `msg_detailed_info#276d3ec6 msg_id:long answer_msg_id:long bytes:int status:int = MsgDetailedInfo`
    case msgDetailedInfo(TL.MsgDetailedInfo)
    /// `msg_new_detailed_info#809db6df answer_msg_id:long bytes:int status:int = MsgDetailedInfo`
    case msgNewDetailedInfo(TL.MsgNewDetailedInfo)
  }

  /// TL: `msg_detailed_info#276d3ec6 msg_id:long answer_msg_id:long bytes:int status:int = MsgDetailedInfo`
  @TLObject(id: 0x276d3ec6)
  public struct MsgDetailedInfo: Equatable, Sendable {
    public var msgId: Int64
    public var answerMsgId: Int64
    public var bytes: Int32
    public var status: Int32
  }

  /// TL: `msg_new_detailed_info#809db6df answer_msg_id:long bytes:int status:int = MsgDetailedInfo`
  @TLObject(id: 0x809db6df)
  public struct MsgNewDetailedInfo: Equatable, Sendable {
    public var answerMsgId: Int64
    public var bytes: Int32
    public var status: Int32
  }
}
