// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `msg_resend_req#7d861a08 msg_ids:Vector<long> = MsgResendReq`
  @TLObject(id: 0x7d861a08)
  public struct MsgResendReq: Equatable, Sendable {
    public var msgIds: [Int64]
  }
}
