// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `msgs_all_info#8cc0d131 msg_ids:Vector<long> info:bytes = MsgsAllInfo`
  @TLObject(id: 0x8cc0d131)
  public struct MsgsAllInfo: Equatable, Sendable {
    public var msgIds: [Int64]
    public var info: Data
  }
}
