// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `msgs_ack#62d6b459 msg_ids:Vector<long> = MsgsAck`
  @TLObject(id: 0x62d6b459)
  public struct MsgsAck: Equatable, Sendable {
    public var msgIds: [Int64]
  }
}
