// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `msgs_state_req#da69fb52 msg_ids:Vector<long> = MsgsStateReq`
  @TLObject(id: 0xda69fb52)
  public struct MsgsStateReq: Equatable, Sendable {
    public var msgIds: [Int64]
  }
}
