// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `msgs_state_info#04deb57d req_msg_id:long info:bytes = MsgsStateInfo`
  @TLObject(id: 0x04deb57d)
  public struct MsgsStateInfo: Equatable, Sendable {
    public var reqMsgId: Int64
    public var info: Data
  }
}
