// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `new_session_created#9ec20908 first_msg_id:long unique_id:long server_salt:long = NewSession`
  @TLObject(id: 0x9ec20908)
  public struct NewSessionCreated: Equatable, Sendable {
    public var firstMsgId: Int64
    public var uniqueId: Int64
    public var serverSalt: Int64
  }
}
