// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `P_Q_inner_data` (4 constructors).
  @TLType
  public indirect enum PQInnerDataType: Equatable, Sendable {
    /// `p_q_inner_data_dc#a9f55f95 pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 dc:int = P_Q_inner_data`
    case pQInnerDataDc(TL.PQInnerDataDc)
    /// `p_q_inner_data_temp_dc#56fddf88 pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 dc:int expires_in:int = P_Q_inner_data`
    case pQInnerDataTempDc(TL.PQInnerDataTempDc)
    /// `p_q_inner_data#83c95aec pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 = P_Q_inner_data`
    case pQInnerData(TL.PQInnerData)
    /// `p_q_inner_data_temp#3c6a84d4 pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 expires_in:int = P_Q_inner_data`
    case pQInnerDataTemp(TL.PQInnerDataTemp)
  }

  /// TL: `p_q_inner_data_dc#a9f55f95 pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 dc:int = P_Q_inner_data`
  @TLObject(id: 0xa9f55f95)
  public struct PQInnerDataDc: Equatable, Sendable {
    public var pq: Data
    public var p: Data
    public var q: Data
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonce: TLInt256
    public var dc: Int32
  }

  /// TL: `p_q_inner_data_temp_dc#56fddf88 pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 dc:int expires_in:int = P_Q_inner_data`
  @TLObject(id: 0x56fddf88)
  public struct PQInnerDataTempDc: Equatable, Sendable {
    public var pq: Data
    public var p: Data
    public var q: Data
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonce: TLInt256
    public var dc: Int32
    public var expiresIn: Int32
  }

  /// TL: `p_q_inner_data#83c95aec pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 = P_Q_inner_data`
  @TLObject(id: 0x83c95aec)
  public struct PQInnerData: Equatable, Sendable {
    public var pq: Data
    public var p: Data
    public var q: Data
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonce: TLInt256
  }

  /// TL: `p_q_inner_data_temp#3c6a84d4 pq:bytes p:bytes q:bytes nonce:int128 server_nonce:int128 new_nonce:int256 expires_in:int = P_Q_inner_data`
  @TLObject(id: 0x3c6a84d4)
  public struct PQInnerDataTemp: Equatable, Sendable {
    public var pq: Data
    public var p: Data
    public var q: Data
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonce: TLInt256
    public var expiresIn: Int32
  }
}
