// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `pong#347773c5 msg_id:long ping_id:long = Pong`
  @TLObject(id: 0x347773c5)
  public struct Pong: Equatable, Sendable {
    public var msgId: Int64
    public var pingId: Int64
  }
}
