// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `resPQ#05162463 nonce:int128 server_nonce:int128 pq:bytes server_public_key_fingerprints:Vector<long> = ResPQ`
  @TLObject(id: 0x05162463)
  public struct ResPQ: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var pq: Data
    public var serverPublicKeyFingerprints: [Int64]
  }
}
