// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `RpcDropAnswer` (3 constructors).
  @TLType
  public indirect enum RpcDropAnswerType: Equatable, Sendable {
    /// `rpc_answer_unknown#5e2ad36e = RpcDropAnswer`
    case rpcAnswerUnknown(TL.RpcAnswerUnknown)
    /// `rpc_answer_dropped_running#cd78e586 = RpcDropAnswer`
    case rpcAnswerDroppedRunning(TL.RpcAnswerDroppedRunning)
    /// `rpc_answer_dropped#a43ad8b7 msg_id:long seq_no:int bytes:int = RpcDropAnswer`
    case rpcAnswerDropped(TL.RpcAnswerDropped)
  }

  /// TL: `rpc_answer_unknown#5e2ad36e = RpcDropAnswer`
  @TLObject(id: 0x5e2ad36e)
  public struct RpcAnswerUnknown: Equatable, Sendable {
  }

  /// TL: `rpc_answer_dropped_running#cd78e586 = RpcDropAnswer`
  @TLObject(id: 0xcd78e586)
  public struct RpcAnswerDroppedRunning: Equatable, Sendable {
  }

  /// TL: `rpc_answer_dropped#a43ad8b7 msg_id:long seq_no:int bytes:int = RpcDropAnswer`
  @TLObject(id: 0xa43ad8b7)
  public struct RpcAnswerDropped: Equatable, Sendable {
    public var msgId: Int64
    public var seqNo: Int32
    public var bytes: Int32
  }
}
