// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `rpc_error#2144ca19 error_code:int error_message:string = RpcError`
  @TLObject(id: 0x2144ca19)
  public struct RpcError: Equatable, Sendable {
    public var errorCode: Int32
    public var errorMessage: String
  }
}
