// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `rpc_result#f35c6d01 req_msg_id:long result:Object = RpcResult`
  @TLObject(id: 0xf35c6d01)
  public struct RpcResult: Equatable, Sendable {
    public var reqMsgId: Int64
    public var result: TLAnyObject
  }
}
