// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `Server_DH_Params` (2 constructors).
  @TLType
  public indirect enum ServerDHParamsType: Equatable, Sendable {
    /// `server_DH_params_ok#d0e8075c nonce:int128 server_nonce:int128 encrypted_answer:bytes = Server_DH_Params`
    case serverDHParamsOk(TL.ServerDHParamsOk)
    /// `server_DH_params_fail#79cb045d nonce:int128 server_nonce:int128 new_nonce_hash:int128 = Server_DH_Params`
    case serverDHParamsFail(TL.ServerDHParamsFail)
  }

  /// TL: `server_DH_params_ok#d0e8075c nonce:int128 server_nonce:int128 encrypted_answer:bytes = Server_DH_Params`
  @TLObject(id: 0xd0e8075c)
  public struct ServerDHParamsOk: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var encryptedAnswer: Data
  }

  /// TL: `server_DH_params_fail#79cb045d nonce:int128 server_nonce:int128 new_nonce_hash:int128 = Server_DH_Params`
  @TLObject(id: 0x79cb045d)
  public struct ServerDHParamsFail: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonceHash: TLInt128
  }
}
