// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `server_DH_inner_data#b5890dba nonce:int128 server_nonce:int128 g:int dh_prime:bytes g_a:bytes server_time:int = Server_DH_inner_data`
  @TLObject(id: 0xb5890dba)
  public struct ServerDHInnerData: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var g: Int32
    public var dhPrime: Data
    public var gA: Data
    public var serverTime: Int32
  }
}
