// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// The TL type `Set_client_DH_params_answer` (3 constructors).
  @TLType
  public indirect enum SetClientDHParamsAnswerType: Equatable, Sendable {
    /// `dh_gen_ok#3bcbf734 nonce:int128 server_nonce:int128 new_nonce_hash1:int128 = Set_client_DH_params_answer`
    case dhGenOk(TL.DhGenOk)
    /// `dh_gen_retry#46dc1fb9 nonce:int128 server_nonce:int128 new_nonce_hash2:int128 = Set_client_DH_params_answer`
    case dhGenRetry(TL.DhGenRetry)
    /// `dh_gen_fail#a69dae02 nonce:int128 server_nonce:int128 new_nonce_hash3:int128 = Set_client_DH_params_answer`
    case dhGenFail(TL.DhGenFail)
  }

  /// TL: `dh_gen_ok#3bcbf734 nonce:int128 server_nonce:int128 new_nonce_hash1:int128 = Set_client_DH_params_answer`
  @TLObject(id: 0x3bcbf734)
  public struct DhGenOk: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonceHash1: TLInt128
  }

  /// TL: `dh_gen_retry#46dc1fb9 nonce:int128 server_nonce:int128 new_nonce_hash2:int128 = Set_client_DH_params_answer`
  @TLObject(id: 0x46dc1fb9)
  public struct DhGenRetry: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonceHash2: TLInt128
  }

  /// TL: `dh_gen_fail#a69dae02 nonce:int128 server_nonce:int128 new_nonce_hash3:int128 = Set_client_DH_params_answer`
  @TLObject(id: 0xa69dae02)
  public struct DhGenFail: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var newNonceHash3: TLInt128
  }
}
