import SwiftBasicFormat
import SwiftSyntax
import SwiftSyntaxBuilder

/// One generated source file, addressed relative to the output directory.
public struct GeneratedFile: Equatable, Sendable {
  public var path: String
  public var contents: String

  public init(path: String, contents: String) {
    self.path = path
    self.contents = contents
  }
}

/// Assembles top-level declarations into a complete source file.
@_spi(GeneratorInternals) public enum SwiftFile {
  @_spi(GeneratorInternals) public static let header = """
    // Generated by mtproto-gen-swift from the Telegram TL schema.
    // DO NOT EDIT: re-run the generator instead.

    """

  /// Renders the file with the standard imports (`TLCoding`, Foundation)
  /// plus any `extraImports` (e.g. the module declaring the root `TL`).
  @_spi(GeneratorInternals) public static func render(
    _ declarations: [DeclSyntax], extraImports: [String] = []
  ) -> String {
    let file = SourceFileSyntax {
      DeclSyntax("import TLCoding")
      for module in extraImports {
        DeclSyntax("import \(raw: module)")
      }
      DeclSyntax(
        """

        #if canImport(FoundationEssentials)
          import FoundationEssentials
        #else
          import Foundation
        #endif
        """
      )
      for declaration in declarations {
        declaration.with(\.leadingTrivia, Trivia.newlines(2) + declaration.leadingTrivia)
      }
    }
    let format = BasicFormat(indentationWidth: .spaces(2))
    var text = SwiftFile.header + file.formatted(using: format).description
    if !text.hasSuffix("\n") { text += "\n" }
    return text
  }

  /// Wraps declarations in `extension TL { … }` / `extension TL.Auth { … }`
  /// and renders the file. Consecutive declarations sharing a scope share
  /// one extension block.
  @_spi(GeneratorInternals) public static func render(
    _ scopedDeclarations: [(scope: String, decl: DeclSyntax)], extraImports: [String] = []
  ) throws -> String {
    var wrappers: [DeclSyntax] = []
    var index = 0
    while index < scopedDeclarations.count {
      let scope = scopedDeclarations[index].scope
      var group: [DeclSyntax] = []
      while index < scopedDeclarations.count, scopedDeclarations[index].scope == scope {
        group.append(scopedDeclarations[index].decl)
        index += 1
      }
      let wrapper = try ExtensionDeclSyntax("extension \(raw: scope)") {
        for declaration in group {
          declaration.with(\.leadingTrivia, Trivia.newlines(2) + declaration.leadingTrivia)
        }
      }
      wrappers.append(DeclSyntax(wrapper))
    }
    return render(wrappers, extraImports: extraImports)
  }
}

extension ResolvedSchema {
  // MARK: - Namespace declarations

  /// `Support/Namespaces.swift` — the root `TL` enum and one nested caseless enum
  /// per TL namespace. Everything else extends these.
  ///
  /// With `rootNamespaceModule` set, that module owns `TL`: it is re-exported
  /// here instead of redeclared. See <doc:ExtendingASchema>.
  func namespacesFile(
    visibility: String, rootNamespaceModule: String? = nil
  ) throws -> GeneratedFile {
    var declarations: [DeclSyntax] = [
      rootNamespaceModule.map { module in
        DeclSyntax(
          """
          /// The root `TL` namespace is declared in \(raw: module); re-export
          /// it so this module presents the complete `TL.*` surface.
          @_exported import \(raw: module)
          """
        )
      }
        ?? DeclSyntax(
          """
          /// Root namespace for every declaration generated from the TL schema.
          \(raw: visibility) enum TL {}
          """
        )
    ]
    if !namespaceEnumNames.isEmpty {
      let namespaces = try ExtensionDeclSyntax("extension TL") {
        for name in namespaceEnumNames {
          DeclSyntax(
            """
            /// The TL namespace `\(raw: Naming.lowercasedFirst(name)).*`.
            \(raw: visibility) enum \(raw: name) {}
            """
          )
        }
      }
      declarations.append(DeclSyntax(namespaces))
    }
    return GeneratedFile(
      path: "Support/Namespaces.swift",
      contents: SwiftFile.render(declarations))
  }

  // MARK: - Types and methods

  /// `Types/<tl.TypeName>.swift` — the `@TLType` enum for a multi-constructor
  /// type, followed by one `@TLObject` struct per constructor, in the namespace
  /// scope.
  func typeFile(
    _ type: TypeDefinition, visibility: String, extraImports: [String] = []
  ) throws -> GeneratedFile {
    var declarations: [(scope: String, decl: DeclSyntax)] = []
    if let enumName = type.swiftEnumName {
      declarations.append((enumName.scope, try typeEnumDecl(type, visibility: visibility)))
    }
    for constructor in type.constructors {
      declarations.append(
        (
          constructor.swiftName.scope,
          try objectStructDecl(
            tlDeclaration: constructor.tlDeclaration,
            constructorID: constructor.constructorID,
            swiftName: constructor.swiftName,
            fields: constructor.fields,
            combinator: constructor.tlName,
            visibility: visibility)
        ))
    }
    return GeneratedFile(
      path: "Types/\(type.tlName).swift",
      contents: try SwiftFile.render(declarations, extraImports: extraImports))
  }

  /// `Methods/<tl.methodName>.swift` — the request struct; the TLCoding
  /// macro also attaches the `TLFunction` conformance carrying the method's
  /// result type.
  func methodFile(
    _ method: Method, visibility: String, extraImports: [String] = []
  ) throws -> GeneratedFile {
    let shape: ObjectStructShape
    if method.isGeneric {
      shape = try genericFunctionShape(method, visibility: visibility)
    } else {
      let returnType = try swiftType(for: method.returnType, in: method.tlName)
      shape = ObjectStructShape(attributeSuffix: ", returning: \(returnType).self")
    }
    let declaration = try objectStructDecl(
      tlDeclaration: method.tlDeclaration,
      constructorID: method.constructorID,
      swiftName: method.swiftName,
      fields: method.fields,
      combinator: method.tlName,
      visibility: visibility,
      shape: shape)
    return GeneratedFile(
      path: "Methods/\(method.tlName).swift",
      contents: try SwiftFile.render(
        [(method.swiftName.scope, declaration)], extraImports: extraImports))
  }
}
