// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `destroy_auth_key#d1435160 = DestroyAuthKeyRes`
  @TLObject(id: 0xd1435160, returning: TL.DestroyAuthKeyResType.self)
  public struct DestroyAuthKey: Equatable, Sendable {
  }
}
