// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `destroy_session#e7512126 session_id:long = DestroySessionRes`
  @TLObject(id: 0xe7512126, returning: TL.DestroySessionResType.self)
  public struct DestroySession: Equatable, Sendable {
    public var sessionId: Int64
  }
}
