// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `get_future_salts#b921bd04 num:int = FutureSalts`
  @TLObject(id: 0xb921bd04, returning: TL.FutureSalts.self)
  public struct GetFutureSalts: Equatable, Sendable {
    public var num: Int32
  }
}
