// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `ping_delay_disconnect#f3427b8c ping_id:long disconnect_delay:int = Pong`
  @TLObject(id: 0xf3427b8c, returning: TL.Pong.self)
  public struct PingDelayDisconnect: Equatable, Sendable {
    public var pingId: Int64
    public var disconnectDelay: Int32
  }
}
