// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `ping#7abe77ec ping_id:long = Pong`
  @TLObject(id: 0x7abe77ec, returning: TL.Pong.self)
  public struct Ping: Equatable, Sendable {
    public var pingId: Int64
  }
}
