// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `req_pq_multi#be7e8ef1 nonce:int128 = ResPQ`
  @TLObject(id: 0xbe7e8ef1, returning: TL.ResPQ.self)
  public struct ReqPqMulti: Equatable, Sendable {
    public var nonce: TLInt128
  }
}
