// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `req_pq#60469778 nonce:int128 = ResPQ`
  @TLObject(id: 0x60469778, returning: TL.ResPQ.self)
  public struct ReqPq: Equatable, Sendable {
    public var nonce: TLInt128
  }
}
