// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `req_pq_multi_new#51b410fd nonce:int128 = ResPQ`
  @TLObject(id: 0x51b410fd, returning: TL.ResPQ.self)
  public struct ReqPqMultiNew: Equatable, Sendable {
    public var nonce: TLInt128
  }
}
