// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `req_DH_params#d712e4be nonce:int128 server_nonce:int128 p:bytes q:bytes public_key_fingerprint:long encrypted_data:bytes = Server_DH_Params`
  @TLObject(id: 0xd712e4be, returning: TL.ServerDHParamsType.self)
  public struct ReqDHParams: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var p: Data
    public var q: Data
    public var publicKeyFingerprint: Int64
    public var encryptedData: Data
  }
}
