// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `rpc_drop_answer#58e4a740 req_msg_id:long = RpcDropAnswer`
  @TLObject(id: 0x58e4a740, returning: TL.RpcDropAnswerType.self)
  public struct RpcDropAnswer: Equatable, Sendable {
    public var reqMsgId: Int64
  }
}
