// Generated by mtproto-gen-swift from the Telegram TL schema.
// DO NOT EDIT: re-run the generator instead.
import TLCoding
#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

extension TL {

  /// TL: `set_client_DH_params#f5045f1f nonce:int128 server_nonce:int128 encrypted_data:bytes = Set_client_DH_params_answer`
  @TLObject(id: 0xf5045f1f, returning: TL.SetClientDHParamsAnswerType.self)
  public struct SetClientDHParams: Equatable, Sendable {
    public var nonce: TLInt128
    public var serverNonce: TLInt128
    public var encryptedData: Data
  }
}
